# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 753cde12fa44dcfac1423241abf9d38c404f127ca9b5049b593a6601767e517366adc1ad329b12f2643ffb7fed0ce38eacf2e8c957466885420931f5d350e7ca

test:
  secret_key_base: f474fb08bf8ed0d23fad9a05a53307c69e54e33866fe7e4dff8956ac751842740b9fe5a99b4d4f82caf3f9dd62807634137d3dbb79d771680860f94c75edbb6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
